site_name: Exostellar SDG Documentation
site_description: Software Defined GPU Documentation.

repo_url: https://github.com/Exostellar/docs/

theme:
  name: readthedocs

plugins:
  - search
  - redoc-tag
  - git-revision-date-localized
