site_name: Exostellar SDG Documentation
site_description: Software Defined GPU Documentation.

repo_url: https://github.com/Exostellar/docs/

theme:
  name: material

plugins:
  - search
  - git-revision-date-localized
  - mermaid2
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Overview: index.md
  - Getting Started:
    - Introduction: getting-started/intro.md
    - Self-Hosted Installation: getting-started/install-selfhosted.md
    - AWS Installation: getting-started/install-aws.md
    - Azure Installation: getting-started/install-azure.md
    - GCP Installation: getting-started/install-gcp.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Cluster Operations:
    - Introduction: clusterops/intro.md
    - API: clusterops/api.md
