openapi: 3.0.3
info:
  title: Sample API
  description: A simple API to demonstrate OpenAPI 3.0.3 syntax
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /items:
    get:
      summary: List all items
      operationId: listItems
      tags:
        - items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      operationId: createItem
      tags:
        - items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created

  /items/{itemId}:
    get:
      summary: Get a specific item by ID
      operationId: getItem
      tags:
        - items
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          example: "abc123"
        name:
          type: string
          example: "Sample Item"
        description:
          type: string
          example: "This is a sample item"
